# Jantar de Dança
- title: Jantar e Dança
  description: Você vai jantar e depois dançar muito!
  img: talheres-de-bebe.png
  alt: jantar e dança
# Hora dos Coquetéis
- title: Hora dos Coquetéis
  description: Aproveite os drinks à vontade, cortesia do Pub 128
  img: coqueteis.png
  alt: hora dos coqueteis
# Karaokê a Noite Toda
- title: Karaokê a Noite Toda
  description: Cante bem altto todas as suas músicas favoritas dos anos 80 a noite toda!
  img: microphone.png
  alt: karaokẽ a noite toda